# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import agos_pb2 as proto_dot_agos__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/agos_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub(object):
    """─── Agent Service ──────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitTask = channel.unary_unary(
                '/agos.v1.AgentService/SubmitTask',
                request_serializer=proto_dot_agos__pb2.SubmitTaskRequest.SerializeToString,
                response_deserializer=proto_dot_agos__pb2.SubmitTaskResponse.FromString,
                _registered_method=True)
        self.GetTaskStatus = channel.unary_unary(
                '/agos.v1.AgentService/GetTaskStatus',
                request_serializer=proto_dot_agos__pb2.GetTaskStatusRequest.SerializeToString,
                response_deserializer=proto_dot_agos__pb2.TaskStatusResponse.FromString,
                _registered_method=True)
        self.StreamTaskEvents = channel.unary_stream(
                '/agos.v1.AgentService/StreamTaskEvents',
                request_serializer=proto_dot_agos__pb2.StreamTaskEventsRequest.SerializeToString,
                response_deserializer=proto_dot_agos__pb2.TaskEvent.FromString,
                _registered_method=True)
        self.ListAgents = channel.unary_unary(
                '/agos.v1.AgentService/ListAgents',
                request_serializer=proto_dot_agos__pb2.ListAgentsRequest.SerializeToString,
                response_deserializer=proto_dot_agos__pb2.ListAgentsResponse.FromString,
                _registered_method=True)
        self.RegisterAgent = channel.unary_unary(
                '/agos.v1.AgentService/RegisterAgent',
                request_serializer=proto_dot_agos__pb2.RegisterAgentRequest.SerializeToString,
                response_deserializer=proto_dot_agos__pb2.RegisterAgentResponse.FromString,
                _registered_method=True)


class AgentServiceServicer(object):
    """─── Agent Service ──────────────────────────────────────────
    """

    def SubmitTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTaskEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAgents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterAgent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTask,
                    request_deserializer=proto_dot_agos__pb2.SubmitTaskRequest.FromString,
                    response_serializer=proto_dot_agos__pb2.SubmitTaskResponse.SerializeToString,
            ),
            'GetTaskStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskStatus,
                    request_deserializer=proto_dot_agos__pb2.GetTaskStatusRequest.FromString,
                    response_serializer=proto_dot_agos__pb2.TaskStatusResponse.SerializeToString,
            ),
            'StreamTaskEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTaskEvents,
                    request_deserializer=proto_dot_agos__pb2.StreamTaskEventsRequest.FromString,
                    response_serializer=proto_dot_agos__pb2.TaskEvent.SerializeToString,
            ),
            'ListAgents': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAgents,
                    request_deserializer=proto_dot_agos__pb2.ListAgentsRequest.FromString,
                    response_serializer=proto_dot_agos__pb2.ListAgentsResponse.SerializeToString,
            ),
            'RegisterAgent': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterAgent,
                    request_deserializer=proto_dot_agos__pb2.RegisterAgentRequest.FromString,
                    response_serializer=proto_dot_agos__pb2.RegisterAgentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agos.v1.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agos.v1.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService(object):
    """─── Agent Service ──────────────────────────────────────────
    """

    @staticmethod
    def SubmitTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agos.v1.AgentService/SubmitTask',
            proto_dot_agos__pb2.SubmitTaskRequest.SerializeToString,
            proto_dot_agos__pb2.SubmitTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaskStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agos.v1.AgentService/GetTaskStatus',
            proto_dot_agos__pb2.GetTaskStatusRequest.SerializeToString,
            proto_dot_agos__pb2.TaskStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTaskEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/agos.v1.AgentService/StreamTaskEvents',
            proto_dot_agos__pb2.StreamTaskEventsRequest.SerializeToString,
            proto_dot_agos__pb2.TaskEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAgents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agos.v1.AgentService/ListAgents',
            proto_dot_agos__pb2.ListAgentsRequest.SerializeToString,
            proto_dot_agos__pb2.ListAgentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterAgent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agos.v1.AgentService/RegisterAgent',
            proto_dot_agos__pb2.RegisterAgentRequest.SerializeToString,
            proto_dot_agos__pb2.RegisterAgentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AuthServiceStub(object):
    """─── Auth Service ───────────────────────────────────────────
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/agos.v1.AuthService/Login',
                request_serializer=proto_dot_agos__pb2.LoginRequest.SerializeToString,
                response_deserializer=proto_dot_agos__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.RefreshToken = channel.unary_unary(
                '/agos.v1.AuthService/RefreshToken',
                request_serializer=proto_dot_agos__pb2.RefreshTokenRequest.SerializeToString,
                response_deserializer=proto_dot_agos__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.CreateAPIKey = channel.unary_unary(
                '/agos.v1.AuthService/CreateAPIKey',
                request_serializer=proto_dot_agos__pb2.CreateAPIKeyRequest.SerializeToString,
                response_deserializer=proto_dot_agos__pb2.CreateAPIKeyResponse.FromString,
                _registered_method=True)
        self.RevokeAPIKey = channel.unary_unary(
                '/agos.v1.AuthService/RevokeAPIKey',
                request_serializer=proto_dot_agos__pb2.RevokeAPIKeyRequest.SerializeToString,
                response_deserializer=proto_dot_agos__pb2.RevokeAPIKeyResponse.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """─── Auth Service ───────────────────────────────────────────
    """

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateAPIKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeAPIKey(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=proto_dot_agos__pb2.LoginRequest.FromString,
                    response_serializer=proto_dot_agos__pb2.LoginResponse.SerializeToString,
            ),
            'RefreshToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshToken,
                    request_deserializer=proto_dot_agos__pb2.RefreshTokenRequest.FromString,
                    response_serializer=proto_dot_agos__pb2.LoginResponse.SerializeToString,
            ),
            'CreateAPIKey': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateAPIKey,
                    request_deserializer=proto_dot_agos__pb2.CreateAPIKeyRequest.FromString,
                    response_serializer=proto_dot_agos__pb2.CreateAPIKeyResponse.SerializeToString,
            ),
            'RevokeAPIKey': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeAPIKey,
                    request_deserializer=proto_dot_agos__pb2.RevokeAPIKeyRequest.FromString,
                    response_serializer=proto_dot_agos__pb2.RevokeAPIKeyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agos.v1.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agos.v1.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """─── Auth Service ───────────────────────────────────────────
    """

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agos.v1.AuthService/Login',
            proto_dot_agos__pb2.LoginRequest.SerializeToString,
            proto_dot_agos__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agos.v1.AuthService/RefreshToken',
            proto_dot_agos__pb2.RefreshTokenRequest.SerializeToString,
            proto_dot_agos__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateAPIKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agos.v1.AuthService/CreateAPIKey',
            proto_dot_agos__pb2.CreateAPIKeyRequest.SerializeToString,
            proto_dot_agos__pb2.CreateAPIKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeAPIKey(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agos.v1.AuthService/RevokeAPIKey',
            proto_dot_agos__pb2.RevokeAPIKeyRequest.SerializeToString,
            proto_dot_agos__pb2.RevokeAPIKeyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
